"""ajout du departement au schema et suppression de la promotion

Revision ID: 0dfc57ebff4e
Revises: 3f4e556ce23d
Create Date: 2019-02-05 10:50:51.149834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dfc57ebff4e'
down_revision = '3f4e556ce23d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions_nom'), 'promotions', ['nom'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promotions_nom'), table_name='promotions')
    op.drop_table('promotions')
    # ### end Alembic commands ###
