"""contrainte unique a la promotion et ajout du pourcentage a l etudiant

Revision ID: 31b09e62ff25
Revises: d776e2cb5cba
Create Date: 2019-02-05 10:25:25.053236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31b09e62ff25'
down_revision = 'd776e2cb5cba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_promotions_departement', table_name='promotions')
    op.create_index(op.f('ix_promotions_departement'), 'promotions', ['departement'], unique=True)
    op.add_column('students', sa.Column('pourcentage', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_students_pourcentage'), 'students', ['pourcentage'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_pourcentage'), table_name='students')
    op.drop_column('students', 'pourcentage')
    op.drop_index(op.f('ix_promotions_departement'), table_name='promotions')
    op.create_index('ix_promotions_departement', 'promotions', ['departement'], unique=False)
    # ### end Alembic commands ###
