"""premiere migration

Revision ID: 3b5cf265e660
Revises: 
Create Date: 2019-02-06 07:38:06.346213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b5cf265e660'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departements_nom'), 'departements', ['nom'], unique=True)
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('niveau', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions_niveau'), 'promotions', ['niveau'], unique=True)
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=20), nullable=True),
    sa.Column('street_name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schools_city'), 'schools', ['city'], unique=False)
    op.create_index(op.f('ix_schools_email'), 'schools', ['email'], unique=True)
    op.create_index(op.f('ix_schools_name'), 'schools', ['name'], unique=False)
    op.create_index(op.f('ix_schools_state'), 'schools', ['state'], unique=False)
    op.create_index(op.f('ix_schools_street_name'), 'schools', ['street_name'], unique=False)
    op.create_table('AdminSchools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_AdminSchools_email'), 'AdminSchools', ['email'], unique=True)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=15), nullable=True),
    sa.Column('last_name', sa.String(length=15), nullable=True),
    sa.Column('forename', sa.String(length=15), nullable=True),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('birth', sa.Date(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('Departement_id', sa.Integer(), nullable=True),
    sa.Column('Promotion_id', sa.Integer(), nullable=True),
    sa.Column('pourcentage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Departement_id'], ['departements.id'], ),
    sa.ForeignKeyConstraint(['Promotion_id'], ['promotions.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_first_name'), 'students', ['first_name'], unique=False)
    op.create_index(op.f('ix_students_forename'), 'students', ['forename'], unique=False)
    op.create_index(op.f('ix_students_last_name'), 'students', ['last_name'], unique=False)
    op.create_index(op.f('ix_students_pourcentage'), 'students', ['pourcentage'], unique=False)
    op.create_index(op.f('ix_students_sex'), 'students', ['sex'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_sex'), table_name='students')
    op.drop_index(op.f('ix_students_pourcentage'), table_name='students')
    op.drop_index(op.f('ix_students_last_name'), table_name='students')
    op.drop_index(op.f('ix_students_forename'), table_name='students')
    op.drop_index(op.f('ix_students_first_name'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_AdminSchools_email'), table_name='AdminSchools')
    op.drop_table('AdminSchools')
    op.drop_index(op.f('ix_schools_street_name'), table_name='schools')
    op.drop_index(op.f('ix_schools_state'), table_name='schools')
    op.drop_index(op.f('ix_schools_name'), table_name='schools')
    op.drop_index(op.f('ix_schools_email'), table_name='schools')
    op.drop_index(op.f('ix_schools_city'), table_name='schools')
    op.drop_table('schools')
    op.drop_index(op.f('ix_promotions_niveau'), table_name='promotions')
    op.drop_table('promotions')
    op.drop_index(op.f('ix_departements_nom'), table_name='departements')
    op.drop_table('departements')
    # ### end Alembic commands ###
