"""no promotion

Revision ID: 3f4e556ce23d
Revises: 31b09e62ff25
Create Date: 2019-02-05 10:38:47.667331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f4e556ce23d'
down_revision = '31b09e62ff25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_promotions_classe', table_name='promotions')
    op.drop_index('ix_promotions_departement', table_name='promotions')
    op.drop_table('promotions')
    op.create_index(op.f('ix_students_pourcentage'), 'students', ['pourcentage'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_pourcentage'), table_name='students')
    op.create_table('promotions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('classe', sa.INTEGER(), nullable=True),
    sa.Column('departement', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_promotions_departement', 'promotions', ['departement'], unique=1)
    op.create_index('ix_promotions_classe', 'promotions', ['classe'], unique=False)
    # ### end Alembic commands ###
