"""ajout de la promotion

Revision ID: d776e2cb5cba
Revises: 
Create Date: 2019-02-05 10:14:51.770387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd776e2cb5cba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classe', sa.Integer(), nullable=True),
    sa.Column('departement', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions_classe'), 'promotions', ['classe'], unique=False)
    op.create_index(op.f('ix_promotions_departement'), 'promotions', ['departement'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promotions_departement'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_classe'), table_name='promotions')
    op.drop_table('promotions')
    # ### end Alembic commands ###
